### ISSUE TITLE
Pack should use requests() lib

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm-Exchange/stackstorm-icinga2#2]
This pack should be rewritten to use the requests() library, rather than pycurl. Amongst other things, this will avoid the Unicode issues, and the need for additional system packages.

**Comment by lakshmi-kannan** [comment]
@LindsayHill https://github.com/twalk6/stackstorm-icinga2req

**Comment by LindsayHill** [comment]
Resolved by #9
