### ISSUE TITLE
pack doesn't get registered

### ISSUE THREAD

**Issue by batmanme** [StackStorm-Exchange/stackstorm-icinga2#8]
Hi,

Getting below issue while registering the pack.

2018-12-19 09:40:43,596 ERROR [-] Pack "icinga2" contains a deprecated config.yaml file (/opt/stackstorm/packs/icinga2/config.yaml). Support for "config.yaml" files has been deprecated in StackStorm v1.6.0 in favor of config.schema.yaml config schema files and config files in /opt/stackstorm/configs/ directory. Support for config.yaml files has been removed in the release (v2.4.0) so please migrate. For more information please refer to https://docs.stackstorm.com/reference/pack_configs.html

**Comment by LindsayHill** [comment]
This pack does not contain a config.yaml file. It has not done so for at least 2 years. Did you manually create one, or install an old version of this pack?

**Comment by batmanme** [comment]
I manually created config.schema.yaml and that did the fix. Now i'm able to register the package.

**Comment by LindsayHill** [comment]
The pack already contains a config.schema.yaml, here https://github.com/StackStorm-Exchange/stackstorm-icinga2/blob/master/config.schema.yaml

I don’t understand why you needed to create one

**Comment by Kami** [comment]
How did you install the pack?

It doesn't look like you are using version from github, or you are using some older version.

**Comment by batmanme** [comment]
st2 pack install icinga2 is the command i ran.

**Comment by LindsayHill** [comment]
> st2 pack install icinga2 is the command i ran.

I just checked again here. If you run `st2 pack install icinga2`, it installs the latest version. That does not include a `config.yaml` file. 

The only ways I can see that you could have ended up with a `config.yaml` file is these options:
1/ You manually created a `config.yaml` file
2/ You installed version 0.2.0 with `st2 pack install icinga2=0.2.0`
3/ You installed from some other repository, e.g. some internal repository. If your system is configured to use a non-default StackStorm index, that could be pulling content from some other repository.

You could check number 3 by doing this:

```shell
cd /opt/stackstorm/packs/icinga2
git remote -v
git branch
cat pack.yaml
```

This should look something like this:
```shell
vagrant@stackstorm:/opt/stackstorm/packs/icinga2$ git remote -v
origin	https://github.com/StackStorm-Exchange/stackstorm-icinga2 (fetch)
origin	https://github.com/StackStorm-Exchange/stackstorm-icinga2 (push)
vagrant@stackstorm:/opt/stackstorm/packs/icinga2$ git branch
* master
vagrant@stackstorm:/opt/stackstorm/packs/icinga2$ cat pack.yaml
---
ref: icinga2
name: icinga2
description: Icinga2 Monitoring
keywords:
  - icinga
  - monitoring
  - alerting
version: 0.3.3
author: Igor Cherkaev
email: emptywee@protonmail.ch
vagrant@stackstorm:/opt/stackstorm/packs/icinga2$
```

**Comment by batmanme** [comment]
I'm sure i did not run step 1,2. And i don't see much difference in output on checking step 3 as well. 

ubuntu@St2storm:~$ cd /opt/stackstorm/packs/icinga2
ubuntu@St2storm:/opt/stackstorm/packs/icinga2$ git remote -v
origin  https://github.com/StackStorm-Exchange/stackstorm-icinga2 (fetch)
origin  https://github.com/StackStorm-Exchange/stackstorm-icinga2 (push)
ubuntu@St2storm:/opt/stackstorm/packs/icinga2$ git branch
* master
ubuntu@St2storm:/opt/stackstorm/packs/icinga2$ cat pack.yaml
---
ref: icinga2
name: icinga2
description: Icinga2 Monitoring
keywords:
  - icinga
  - monitoring
  - alerting
version: 0.3.3
author: Igor Cherkaev
email: emptywee@protonmail.ch

I installed different version of pycurl 7.43.0.2 due to installation issues. That's the only change i did as far as i remember.

**Comment by LindsayHill** [comment]
I have no idea how you could have ended up with a config.yaml file then. If you can document a way to reproduce it, reopen the issue.
